#include "http_page.h"

/**
 * Простая HTML-страница с JS:
 *  - показывает температуры,
 *  - чекбоксы для on1/2/3,
 *  - периодически опрашивает /state,
 *  - отправляет новые значения на /set.
 */
const char http_index_html[] =
"<!DOCTYPE html>\r\n"
"<html>\r\n"
"<head>\r\n"
"  <meta charset=\"UTF-8\">\r\n"
"  <title>STM32 HTTP Monitor</title>\r\n"
"  <style>\r\n"
"    body { font-family: Arial, sans-serif; background-color: #222; color: #eee; }\r\n"
"    .card { border: 1px solid #555; border-radius: 8px; padding: 16px; margin: 16px auto; max-width: 400px; }\r\n"
"    h1 { font-size: 20px; text-align: center; }\r\n"
"    table { width: 100%; border-collapse: collapse; }\r\n"
"    th, td { padding: 6px; text-align: left; }\r\n"
"    th { border-bottom: 1px solid #555; }\r\n"
"  </style>\r\n"
"</head>\r\n"
"<body>\r\n"
"  <div class=\"card\">\r\n"
"    <h1>STM32 Room Monitor</h1>\r\n"
"    <h2>Температуры</h2>\r\n"
"    <table>\r\n"
"      <tr><th>Канал</th><th>Температура, &deg;C</th></tr>\r\n"
"      <tr><td>T1</td><td><span id=\"t1\">--</span></td></tr>\r\n"
"      <tr><td>T2</td><td><span id=\"t2\">--</span></td></tr>\r\n"
"      <tr><td>T3</td><td><span id=\"t3\">--</span></td></tr>\r\n"
"    </table>\r\n"
"\r\n"
"    <h2>Розетки</h2>\r\n"
"    <table>\r\n"
"      <tr><th>Розетка</th><th>Состояние</th></tr>\r\n"
"      <tr><td>Socket 1</td><td><input type=\"checkbox\" id=\"on1\" onchange=\"sendSet()\"></td></tr>\r\n"
"      <tr><td>Socket 2</td><td><input type=\"checkbox\" id=\"on2\" onchange=\"sendSet()\"></td></tr>\r\n"
"      <tr><td>Socket 3</td><td><input type=\"checkbox\" id=\"on3\" onchange=\"sendSet()\"></td></tr>\r\n"
"    </table>\r\n"
"\r\n"
"    <p id=\"status\" style=\"font-size: 12px; color: #aaa; margin-top: 10px;\">\r\n"
"      Статус: ---\r\n"
"    </p>\r\n"
"  </div>\r\n"
"\r\n"
"<script>\r\n"
"function updateState() {\r\n"
"  fetch('/state')\r\n"
"    .then(function(resp) { return resp.json(); })\r\n"
"    .then(function(data) {\r\n"
"      document.getElementById('t1').textContent = data.t1.toFixed(1);\r\n"
"      document.getElementById('t2').textContent = data.t2.toFixed(1);\r\n"
"      document.getElementById('t3').textContent = data.t3.toFixed(1);\r\n"
"\r\n"
"      document.getElementById('on1').checked = !!data.on1;\r\n"
"      document.getElementById('on2').checked = !!data.on2;\r\n"
"      document.getElementById('on3').checked = !!data.on3;\r\n"
"\r\n"
"      document.getElementById('status').textContent =\r\n"
"        'Статус: обновлено ' + new Date().toLocaleTimeString();\r\n"
"    })\r\n"
"    .catch(function(err) {\r\n"
"      document.getElementById('status').textContent =\r\n"
"        'Статус: ошибка связи (' + err + ')';\r\n"
"    });\r\n"
"}\r\n"
"\r\n"
"function sendSet() {\r\n"
"  var on1 = document.getElementById('on1').checked ? 1 : 0;\r\n"
"  var on2 = document.getElementById('on2').checked ? 1 : 0;\r\n"
"  var on3 = document.getElementById('on3').checked ? 1 : 0;\r\n"
"\r\n"
"  var params = 'on1=' + on1 + '&on2=' + on2 + '&on3=' + on3;\r\n"
"  fetch('/set?' + params)\r\n"
"    .then(function(resp) { return resp.text(); })\r\n"
"    .then(function(txt) {\r\n"
"      document.getElementById('status').textContent = 'Статус: ' + txt;\r\n"
"    })\r\n"
"    .catch(function(err) {\r\n"
"      document.getElementById('status').textContent =\r\n"
"        'Статус: ошибка отправки (' + err + ')';\r\n"
"    });\r\n"
"}\r\n"
"\r\n"
"setInterval(updateState, 1000);\r\n"
"window.onload = updateState;\r\n"
"</script>\r\n"
"\r\n"
"</body>\r\n"
"</html>\r\n";
